version: '2'

client:
    build: client/.
    ports:
        - "80:80"
        
server:
    build: server/.
    links:
        - mongo
    ports:
        - "3000:3000"
    environment:
        ENV: production

mongo:
    image: mongo:3.2
    ports:
        - "27017:27017"
    volumes_from:
        - mongodata

mongodata:
    image: tianon/true
    volumes:
        - /data/db